# Generated by Django 4.0.6 on 2022-07-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_banner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_image',
            new_name='banner_photo',
        ),
    ]
