# Generated by Django 4.0.6 on 2022-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_banner_image_homepage_banner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(blank=True, default='Welcome to my homepage!', max_length=100),
        ),
    ]
