# Generated by Django 4.0.6 on 2022-07-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_socialmediasettings_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
