# Generated by Django 4.0.6 on 2022-07-21 10:38

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cat1_display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat1_display',
            name='cat1_image',
        ),
        migrations.RemoveField(
            model_name='cat1_display',
            name='name',
        ),
        migrations.AddField(
            model_name='cat1_display',
            name='body',
            field=wagtail.fields.StreamField([('name', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True, use_json_field=None),
        ),
    ]
