# Generated by Django 4.0.6 on 2022-07-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_catspage_cat3_image_catspage_cat4_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catspage',
            name='click_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
